everyday_words = [
    "hello", "okay", "thanks", "please", "yes", "no", "maybe", "sure", "really", "great",
    "good", "bad", "fine", "cool", "awesome", "nice", "sorry", "love", "hate", "like",
    "want", "need", "have", "get", "give", "take", "send", "call", "talk", "meet",
    "go", "come", "leave", "stay", "wait", "work", "play", "run", "walk", "drive",
    "eat", "drink", "sleep", "wake", "read", "write", "watch", "listen", "hear", "see",
    "think", "know", "learn", "remember", "forget", "open", "close", "start", "stop", "begin",
    "end", "finish", "help", "try", "use", "find", "lose", "buy", "sell", "pay",
    "money", "time", "day", "night", "morning", "evening", "today", "tomorrow", "yesterday", "week",
    "month", "year", "now", "later", "soon", "always", "never", "sometimes", "often", "usually",
    "home", "house", "room", "bed", "chair", "table", "phone", "laptop", "computer", "screen",
    "keyboard", "mouse", "internet", "email", "message", "text", "chat", "app", "website", "link",
    "file", "folder", "photo", "picture", "video", "music", "song", "movie", "show", "game",
    "book", "story", "news", "article", "blog", "weather", "travel", "trip", "holiday", "vacation",
    "school", "class", "teacher", "student", "test", "exam", "grade", "job", "boss", "team",
    "friend", "family", "parent", "child", "baby", "dog", "cat", "food", "water", "coffee",
    "tea", "juice", "milk", "bread", "rice", "fruit", "vegetable", "meat", "fish", "egg",
    "salt", "pepper", "sugar", "butter", "oil", "cook", "bake", "boil", "fry", "grill",
    "clean", "wash", "dry", "sweep", "vacuum", "iron", "fold", "shop", "drive", "park",
    "walk", "run", "jump", "sit", "stand", "laugh", "cry", "smile", "frown", "angry",
    "happy", "sad", "tired", "bored", "excited", "scared", "worried", "calm", "busy", "free",
    "early", "late", "fast", "slow", "hot", "cold", "warm", "cool", "dark", "light",
    "big", "small", "long", "short", "high", "low", "new", "old", "young", "strong",
    "weak", "clean", "dirty", "easy", "hard", "fun", "boring", "true", "false", "real",
    "open", "close", "up", "down", "left", "right", "inside", "outside", "near", "far",
    "before", "after", "first", "last", "next", "again", "more", "less", "most", "least"
]